In [ ]:
! pip install --upgrade pandas

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.2'

In [3]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [4]:
len(df)

9704

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [6]:
df.fuel_type.nunique()

2

In [7]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df.fuel_efficiency_mpg.max()

25.96722204888372

In [9]:
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [10]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

23.759122836520497

In [11]:
df['horsepower'].median()

149.0

In [12]:
df['horsepower'].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
46.0       1
43.0       1
53.0       1
66.0       1
61.0       1
Name: count, Length: 192, dtype: int64

In [13]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [14]:
df.fillna({'horsepower':152.0}, inplace=True)

In [15]:
df['horsepower'].median()

152.0

- Select all the cars from Asia
- Select only columns vehicle_weight and model_year
- Select the first 7 values
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?

In [16]:
asian_cars = df[df['origin'] == 'Asia']

In [ ]:
asian_cars = asian_cars[['vehicle_weight','model_year']]

In [17]:
asian_cars[['vehicle_weight','model_year']].iloc[:7]

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [18]:
import numpy as np

In [24]:
X = np.array(asian_cars[['vehicle_weight','model_year']].iloc[:7])
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [25]:
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [26]:
X_inv = np.linalg.inv(XTX)
X_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [28]:
temp = np.matmul(X_inv, X.T)
w = np.matmul(temp, y)
w

array([0.01386421, 0.5049067 ])